spring.application.name=demo
spring.security.user.name=admin
spring.security.user.password=password
spring.datasource.url=jdbc:mysql://localhost:3306/securepages
spring.datasource.username=root
spring.datasource.password=Pandey111@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.org.springframework.security=DEBUG

spring.app.jwtSecret=mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
spring.app.jwtExpirationMs=172800000

#email settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=awanikpandey111@gmail.com
spring.mail.password=uvkzwoybqkvsxsmq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# GitHub OAuth2 configuration
spring.security.oauth2.client.registration.github.client-id=Ov23liCiNCBdsm0NRLqB
spring.security.oauth2.client.registration.github.client-secret=a9b8a281a4d6ae1a543ba48a9f0324659acbdb60
spring.security.oauth2.client.registration.github.scope=read:user,user:email

frontend.url=http://localhost:3000


